apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-liga-data
  namespace: go-liga
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
