apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-liga
resources:
  - ../../base
  - sealed-secret.yaml
images:
  - name: ghcr.io/levino/go-ranking
    newTag: 5cb3b209f6d763edef285bbd3c398dab274cb76b
