apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-liga
resources:
  - ../../base
  - sealed-secret.yaml
images:
  - name: ghcr.io/levino/go-ranking
    newTag: f2040663453955be407af5b9c0cdaa616dea4e46
